openapi: 3.1.0
info:
  title: BaaS oAuth
  version: '2021-05-20T17:25:30Z'
  description: oAuth Service
  contact:
    name: PayForward Dev Support
    email: developersupport@payforward.com
servers:
  - url: 'https://baas.auth.us-east-1.amazoncognito.com'
    variables:
      environment:
        enum:
          - baas-dev
          - baas-sandbox
          - baas
        default: baas-devas-dev
paths:
  /oauth2/token:
    parameters: []
    post:
      summary: ''
      operationId: post-oauth2-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../BaaS-API/models/AuthToken.yaml
      description: Obtain oAuth token
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                client_id:
                  type: string
      tags:
        - oAuth
components:
  schemas: {}
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      description: 'Basic Authentication header "Basic {base64 encoded client:password}"'
tags:
  - name: oAuth
